const restaurants = [
  {
    id: "helm",
    name: "Helm",
    stars: 2,
    category: "two_star",
    categoryText: "Two-MICHELIN-Starred Restaurant",
    location: { lat: 14.5579, lng: 121.02525 },
    description:
      "Helm offers a seasonal tasting menu that changes often, blending the chef’s Filipino and European influences into playful and precise dishes. Each visit feels different, with themes that range from nostalgic street food ideas to more experimental flavors. It’s an intimate and polished dining experience built around curiosity and craft.",
    address:
      "3F, The Shops at Ayala Triangle Gardens, Makati Avenue, Makati City, Metro Manila, Philippines",
    contact: "+63 915 909 8647",
    email: "helm.reservations@gmail.com",
    website: "https://www.joshboutwood.net/restaurants/helm",
    image: "assets/helm1.jpg",
  },
  {
    id: "celera",
    name: "Celera",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.5669, lng: 121.008 },
    description: `Celera brings together Japanese, Chinese, and Singaporean inspirations in a cozy, low-lit setting. The kitchen focuses on umami-rich flavors, using techniques like dashi, light smoking, and fermentation. The dishes are creative but comforting, matched with warm service and thoughtful presentation.`,
    address:
      "3F, Comuna, 238 Pablo Ocampo Extension, Makati, Metro Manila, 1203, The Philippines",
    contact: "+63 917 501 3077",
    email: "reservations@restaurantcelera.com",
    website: "https://restaurantcelera.com/",
    image: "assets/celera1.jpg",
  },
  {
    id: "hapag",
    name: "Hapag",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.564583, lng: 121.036944 },
    description:
      'Hapag reimagines Filipino cuisine with modern techniques while staying grounded in familiar flavors. The chefs transform local ingredients into refined dishes that feel both fresh and nostalgic. It’s a personal, thoughtful dining experience that highlights regional traditions through a contemporary lens.',
    address:
      "7th floor, The Balmori Suites Hidalgo Drive, Rockwell Center, Makati, Metro Manila, Philippines",
    contact: "+63 917 888 5757",
    email: "hello@hapagmnl.com",
    website: "https://www.hapagmnl.com/",
    image: "assets/hapag1.jpg",
  },
  {
    id: "linamnam",
    name: "Linamnam",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.473583, lng: 121.041639 },
    description:
      "Linamnam is an intimate dining space where the chef serves deeply personal dishes inspired by regional Filipino traditions. The menu changes often and is built on thoughtful combinations like lamb dumplings, seafood broths, and seasonal desserts. With only a handful of seats, it feels like a warm, memorable meal in a home rather than a restaurant.",
    address:
      "31, Greenvale 2, Marcelo Green Village, Parañaque, Metro Manila, Philippines",
    contact: "+63 917 573 0246",
    email: "",
    website: "https://linamnammnl.cococart.co/",
    image: "assets/linamnam1.jpg",
  },
  {
    id: "asador_alfonso",
    name: "Asador Alfonso",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.473583, lng: 121.041639 },
    description:
      'Asador Alfonso sits on a peaceful property outside Manila, offering a countryside escape paired with bold Spanish flavors. Premium ingredients and wood-fire techniques define the menu, from perfectly roasted meats to delicately aged cuts. The relaxed setting, attentive service, and rustic elegance make it a destination worth the drive.',
    address: "Lot-3308, Barangay Road, Alfonso, Cavite, Philippines",
    contact: "+63 917 150 7621",
    email: "reservations@asadoralfonso.com",
    website: "https://www.asadoralfonso.com/",
    image: "assets/asador_alfonso1.jpg",
  },
  {
    id: "kasa_palma",
    name: "Kása Palma",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.565972, lng: 121.034389 },
    description:
      "A calm, tropical-inspired dining space with woven lamps and greenery sets the tone at Kása Palma. The menu blends French technique with flavors from Latin America and Asia, all brought together with a touch of wood-fire cooking. Whether you sit at the counter or the terrace, dishes feel expressive, refined, and built around quality local ingredients.",
    address: "6042 R. Palma, Poblacion, Makati - Metro Manila, Philippines",
    contact: "+63 917 155 9669",
    email: "reservations@asadoralfonso.com",
    website: "https://www.instagram.com/kasapalma",
    image: "assets/kasa_palma1.jpg",
  },
  {
    id: "gallery_by_chele",
    name: "Gallery by Chele",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.559, lng: 121.056139 },
    description:
      "Gallery by Chele focuses on creativity, sustainability, and local produce. Instead of à la carte, they offer curated tasting menus that highlight ingredients from around the Philippines. Each course is crafted with modern technique and a strong respect for farmers and small producers, creating a thoughtful and educational dining experience.",
    address:
      "5F, Clipp Center, 11th Avenue corner 39th Street, Bonifacio Global City, Taguig - Metro Manila, Philippines",
    contact: "+63 917 546 1673",
    email: "reservations@gallerybychele.com",
    website: "https://gallerybychele.com/",
    image: "assets/gallery_by_chele1.jpg",
  },
  {
    id: "toyo_eatery",
    name: "Toyo Eatery",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.5311389, lng: 121.0226389 },
    description: `Toyo Eatery celebrates Filipino flavors through fermentation, precise seasoning, and time-honored kitchen practices. The menu highlights simple ingredients that undergo slow, careful preparation. From shared meals served on banana leaves to more delicate plates, the restaurant offers a refined take on everyday Filipino staples.`,
    address:
      "The Alley at Karrivin, Karrivin Plaza, 2316 Chino Roces Avenue Extension, Makati - Metro Manila, Philippines",
    contact: "+63 917 546 1673",
    email: "reservations@toyoeatery.com",
    website: "https://toyoeatery.com/",
    image: "assets/toyo_eatery1.jpg",
  },
  {
    id: "inato",
    name: "Inatô",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.5313056, lng: 121.02275 },
    description: `Inatô is a small, elegant counter-style restaurant where just a few diners sit before the open kitchen. The dishes reinterpret Filipino flavors with clean, modern execution—think fresh seafood, bright sauces, and thoughtful textures. Warm interaction from the chefs adds to the intimate, polished feel of the experience.`,
    address:
      "The Alley at Karrivin, Karrivin Plaza, 2316 Chino Roces Avenue Extension, Makati - Metro Manila, 1231, Philippines",
    contact: "+63 945 478 0420",
    email: "reservations@inato.ph",
    website: "https://www.inato.ph/",
    image: "assets/inato1.jpg",
  },
  {
    id: "em_hanoi",
    name: "Em Hà Nội",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.553444, lng: 121.04925 },
    description: `Em Hà Nội brings comforting Vietnamese home-style cooking to a simple, welcoming space. Familiar favorites like phở, grilled pork noodles, and crisp spring rolls are prepared with care and balanced flavors. It’s a cozy stop for honest, satisfying dishes that highlight the warmth of Hanoi-style cuisine.`,
    address:
      "GF, F1 Hotel, 32nd Street corner Lane A, Bonifacio Global City, Taguig - Metro Manila, 1226, The Philippines",
    contact: "+63 981 046 9999",
    email: "emhanoi.mnl@gmail.com",
    website: "https://www.instagram.com/emhanoi.mnl",
    image: "assets/em_hanoi1.jpg",
  },
  {
    id: "palm_grill",
    name: "Palm Grill (Diliman)",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.629167, lng: 121.034111 },
    description: `A cozy and homey spot known for flavors from Southern Mindanao. The dishes highlight roasted coconut, spices, and hearty stews — especially their black beef soup and charcoal-kissed specialties. Welcoming service and warm interior touches make it feel like eating in a relaxed family kitchen.`,
    address:
      "GF, F1 Hotel, 32nd Street corner Lane A, Bonifacio Global City, Taguig - Metro Manila, 1226, The Philippines",
    contact: "+63 908 180 4701",
    email: "palatablechicken@gmail.com",
    website: "https://www.instagram.com/palmgrillph",
    image: "assets/palm_grill1.jpg",
  },
  {
    id: "lampara",
    name: "Lampara",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.563833, lng: 121.032083 },
    description: `Lampara sits quietly on a side street, offering a relaxed space with soft lighting and terrace seating. The menu blends French techniques with Filipino ingredients, creating inventive small plates with clean flavors. From seafood to playful desserts, each dish feels modern yet familiar.`,
    address:
      "2F, 5883 Enriquez Street, Poblacion, Makati - Metro Manila, 1210, Philippines",
    contact: "+63 917 173 5883",
    email: "restaurantlampara@gmail.com",
    website: "https://www.instagram.com/lampara.pob",
    image: "assets/lampara1.jpg",
  },
  {
    id: "your_local",
    name: "Your Local",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.556861, lng: 121.017111 },
    description: `A trendy, buzzing restaurant tucked behind a humble storefront. Inside, it’s urban and upbeat, serving bold Asian-inspired dishes meant for sharing. Their tartare, braised meats, and noodle bowls deliver big flavor without being heavy on the budget — perfect for casual meetups.`,
    address: "106 Esteban, Legazpi Village, Makati - Metro Manila, Philippines",
    contact: "+63 977 487 9236",
    email: "hello@yourlocal.ph",
    website: "https://www.instagram.com/yourlocalph",
    image: "assets/your_local1.jpg",
  },
  {
    id: "cur8",
    name: "CUR8",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.340806, lng: 123.912583 },
    description: `Modern, stylish, and music-filled, CUR8 reimagines Asian comfort food in a fresh, approachable way. The menu is neatly divided into bestsellers, seasonal picks, and healthier choices, making it easy to explore. The lunchtime tasting set is especially popular for offering a bit of everything.`,
    address:
      "Banilad Town Center, Governor M. Cuenco Avenue, Cebu, Cebu, 6000, The Philippines",
    contact: "+63 977 328 0280",
    email: "",
    website: "https://www.instagram.com/CUR8.PH",
    image: "assets/cur81.jpg",
  },
  {
    id: "sarsa",
    name: "Sarsa",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.555944, lng: 121.018222 },
    description: `Sarsa captures the warmth of Filipino comfort cuisine in an unfussy, friendly space. Expect generous servings of grilled, roasted, and stewed favorites, all full of bright flavors. It’s the kind of place where classic dishes shine without any unnecessary complication.`,
    address:
      "109 Rada, Legazpi Village, Makati - Metro Manila, 1229, The Philippines",
    contact: "+63 917 528 0115",
    email: "",
    website: "https://www.instagram.com/sarsa_mnl",
    image: "assets/sarsa1.jpg",
  },
  {
    id: "cochi",
    name: "COCHI",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.555944, lng: 121.018222 },
    description: `COCHI brings a modern take on Filipino celebration dishes, especially their signature roasted suckling pig. The flavors balance herbs, spices, and tender meat, creating a feast-style experience. A simple but stylish interior makes it great for groups and family-style dining.`,
    address:
      "Unit 1, GF, Verve Residences Tower 2, 27th Street corner 9th Avenue, Bonifacio Global City, Taguig - Metro Manila, 1637, Philippines",
    contact: "+63 935 210 1341",
    email: "",
    website: "https://www.instagram.com/cochibymarvin",
    image: "assets/cochi1.jpg",
  },
  {
    id: "the_underbelly",
    name: "The Underbelly",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.531028, lng: 121.022889 },
    description: `A sleek ramen bar located inside The Alley, offering handmade noodles and deeply flavored broths. Each bowl reflects the chef’s love for Japanese cooking, with smoky sides and rich toppings. Clean lines and wood accents give the place a calm, contemporary vibe.`,
    address:
      "The Alley at Karrivin, Karrivin Plaza, 2316 Chino Roces Avenue Extension, Makati - Metro Manila, Philippines",
    contact: "+63 995 217 3796",
    email: "",
    website: "https://www.instagram.com/the.underbelly.ph",
    image: "assets/the_underbelly1.jpg",
  },
  {
    id: "halong",
    name: "Hálong",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.553389, lng: 121.017500 },
    description: `Hálong blends the spontaneity of Mexican cooking with Asian influences, resulting in vibrant dishes full of personality. The menu reflects years of culinary travel and experimentation. Designed by the chef’s brother, the space feels young, artistic, and full of character.`,
    address:
      "U-105, First Midland Condominium Building, 109 Gamboa, Makati - Metro Manila, 1223, Philippines",
    contact: "+63 917 159 4030",
    email: "alrocacompany@gmail.com",
    website: "https://www.instagram.com/halong.restaurant",
    image: "assets/halong1.jpg",
  },
  {
    id: "pares_batchoy_food_house",
    name: "Pares Batchoy Food House",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.30925, lng: 123.890583 },
    description: `A down-to-earth restaurant known for hearty Filipino bowls and family-style dishes. Their stewed beef noodle soup is a crowd favorite, alongside tangy soups and grilled seafood. Friendly staff and illustrated menus make it easy for anyone to enjoy a comforting meal.`,
    address:
      "12 C. Rodriguez Street, Cebu, Cebu, 6000, Philippines",
    contact: "+63 919 009 0707",
    email: "paresbatchoy88@gmail.com",
    website: "https://www.facebook.com/p/Itchoy-Batchoyan-sa-Cebu-by-Pares-Batchoy-Food-House-61550258849279/",
    image: "assets/pares_batchoy_food_house1.jpg",
  },
  {
    id: "taqueria_franco",
    name: "Taquería Franco",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.558888, lng: 121.021777 },
    description: `A playful taquería where Mexican classics meet French technique. Expect tacos filled with creative combinations like foie gras, steak frites, and slow-cooked meats. The monochrome interior and modern plating give it a cool, youthful charm.`,
    address:
      "130 LPL Center, L.P. Leviste Street, Salcedo Village, Makati - Metro Manila, Philippines",
    contact: "+63 945 788 6224",
    email: "contactus.franco@gmail.com",
    website: "https://www.taqueriafranco.com/",
    image: "assets/taqueria_franco1.jpg",
  },
  {
    id: "manam_at_the_triangle",
    name: "Manam at the Triangle",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.556277, lng: 121.024278 },
    description: `This polished and airy branch of Manam elevates their comfort classics with a bright, modern interior filled with Filipino pop art. The menu celebrates the country’s favorite dishes — from slow-cooked meats to grilled chicken — all served in portions great for sharing. It’s casual, lively, and consistently satisfying.`,
    address:
      "Restaurant Arcade, Ayala Triangle Walkways, Makati - Metro Manila, Philippines",
    contact: "+63 967 190 4721",
    email: "speakfreely@momentgroup.ph",
    website: "https://manamtriangle.momentfood.com/",
    image: "assets/manam_at_the_triangle1.jpg",
  },
  {
    id: "los_tacos",
    name: "Los Tacos",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.557222, lng: 121.053361 },
    description: `A sleek, high-ceilinged space showcasing bold Mexican flavors. The open kitchen brings energy to the room as chefs prepare tacos with house-made tortillas and slow-cooked meats. Fresh ceviche, tostadas, and creative fillings round out a menu built around vibrant, confident flavors.`,
    address:
      "UGF, One Uptown Residences, 36th Street, Bonifacio Global City, Taguig - Metro Manila, 1214, Philippines",
    contact: "+63 954 460 3201",
    email: "",
    website: "https://www.tablecheck.com/en/los-tacos-mnl/reserve/message",
    image: "assets/los_tacos1.jpg",
  },
  {
    id: "cabel",
    name: "Cabel",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.593472, lng: 120.992972 },
    description: `Found in a heritage building from the 1930s, Cabel pairs nostalgic Filipino interiors with regional dishes rich in Mindanaoan influence. The warm, garden-side setting enhances rustic classics like deep-fried appetizers and spiced chicken. A relaxing landmark for both casual meals and special gatherings.`,
    address:
      "1153 JP Laurel corner Aguado Street, San Miguel, Manila - Metro Manila, Philippines",
    contact: "+63 915 214 8565",
    email: "bycabel.ph@gmail.com",
    website: "https://www.instagram.com/bycabel.ph",
    image: "assets/cabel1.jpg",
  },
  {
    id: "pilyas_kitchen",
    name: "Pilya's Kitchen",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.565583, lng: 121.036750 },
    description: `Located inside a bustling food hall, this noodle counter specializes in handmade ribbons of chewy noodles inspired by the chef’s Chinese culinary background. Their pork and shrimp wontons are crisp and fragrant, while stir-fried noodle bowls deliver comforting flavors with a playful twist.`,
    address:
      "Stall 11, The Grid - Food Market, Power Plant Mall, Rockwell Drive corner Estrella, Makati - Metro Manila, 1210, Philippines",
    contact: "+63 917 707 7459",
    email: "thegridadmin@tasteless.ph",
    website: "https://thegridfoodmarket.com/pages/pilyas-kitchen-categories",
    image: "assets/pilyas_kitchen1.jpg",
  },
  {
    id: "bolero",
    name: "Bolero",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.548861, lng: 121.049444 },
    description: `A modern Spanish-inspired restaurant with Mediterranean touches and a laid-back sharing style. Crowd favorites include grilled meats, empanadas, and a famously molten cheesecake. The warm lighting and contemporary interior make it an inviting spot for groups and date nights alike.`,
    address:
      "GF, Verve Residences Tower 2, High Street South, 26th 27th Street, Bonifacio Global City, Taguig - Metro Manila, 1634, Philippines",
    contact: "+63 917 120 1228",
    email: "info@bolero.ph",
    website: "https://bolero.ph/",
    image: "assets/bolero1.jpg",
  },
  {
    id: "kumba",
    name: "Kumba",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.446277, lng: 121.021139 },
    description: `Kumba brings together comforting dishes inspired by Chinese, Filipino, and Southeast Asian flavors. The inviting space, soft lighting, and woven accents create a cozy dining backdrop. Their signature fluffy buns filled with tender pork and crunchy toppings offer a comforting bite rooted in home-style cooking.`,
    address:
      "92 Aguirre Avenue, BF Homes, Parañaque - Metro Manila, Philippines",
    contact: "+63 995 106 2879",
    email: "kumbaclub@gmail.com",
    website: "https://www.instagram.com/kumbaph",
    image: "assets/kumba1.jpg",
  },
  {
    id: "la_pita",
    name: "La Pita",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.564139, lng: 121.031528 },
    description: `This intimate Middle Eastern spot features colorful seating, warm sunlight, and the aroma of fresh pita. Dishes are made with deep care — from creamy hummus to slow-cooked lamb and soft desserts. Despite its small size, every plate feels handmade and generous.`,
    address:
      "5652 Don Pedro, Poblacion, Makati - Metro Manila, 1210, Philippines",
    contact: "+63 966 483 5789",
    email: "lapita@gmail.com",
    website: "https://www.instagram.com/lapita.mkt",
    image: "assets/la_pita1.jpg",
  },
  {
    id: "the_pig_and_palm",
    name: "The Pig & Palm",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.312861, lng: 123.904528 },
    description: `A chic restaurant blending European flavors with Cebu’s relaxed island vibe. Pork takes center stage, especially in their tender confit dishes and modern small plates. The wood-and-brick design evokes a modern bistro atmosphere, perfect for sharing and sipping in good company.`,
    address:
      "GF, MSY Tower, Pescadores Road, Cebu Business Park, Cebu, Cebu, 6000, Philippines",
    contact: "+63 917 657 6866",
    email: "",
    website: "https://thepigandpalm.ph/",
    image: "assets/the_pig_and_palm1.jpg",
  },
  {
    id: "brick_corner",
    name: "Brick Corner",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.552333, lng: 121.045111 },
    description: `Bright colors, exposed brick, and warm lighting give this Indian restaurant a vibrant personality. The menu focuses on hearty northern Indian dishes — rich curries, spiced meats, and freshly baked naan from their tandoor. Everything is bold, aromatic, and perfect for a comforting meal.`,
    address:
      "151 Forbeswood Heights, Forbestown Road, Bonifacio Global City, Taguig - Metro Manila, Philippines",
    contact: "+63 918 803 9457",
    email: "",
    website: "https://www.instagram.com/brickcorner.ph",
    image: "assets/brick_corner1.jpg",
  },
  {
    id: "lasa",
    name: "Lasa",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.370806, lng: 123.873611 },
    description: `Surrounded by greenery and panoramic mountain views, Lasa serves refined Filipino dishes in an open-air setting. The vibrant plates — from kinilaw to crispy pork — highlight regional flavors with a modern approach. A peaceful destination for relaxed lunches and scenic dinners.`,
    address:
      "Near Roosevelt Drive, Busay, Cebu, Cebu, 6000, Philippines",
    contact: "+63 966 183 0611",
    email: "",
    website: "https://www.facebook.com/100094288054455",
    image: "assets/lasa1.jpg",
  },
  {
    id: "esmen",
    name: "Esmen",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.292750, lng: 123.894556 },
    description: `A humble neighborhood eatery known for comfort dishes rooted in Cebuano home cooking. The space has a lived-in charm, and meals are served generously — from flavorful stews to fried staples. The casual, family-style atmosphere makes it feel like eating in a relative’s kitchen.`,
    address:
      "10 F. Rallos Street, Pasil, Cebu, Cebu, Philippines",
    contact: "+63 927 302 5936",
    email: "",
    website: "https://www.facebook.com/esmencarinderia/",
    image: "assets/esmen1.jpg",
  },
  {
    id: "abaseria_deli_cafe",
    name: "Abaseria Deli & Cafe",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.326333, lng: 123.912750 },
    description: `Filled with local crafts and nostalgic décor, Abaseria blends restaurant and home. Their dishes lean toward slow-cooked Filipino favorites with warm, familiar flavors. Desserts and coffee are standouts, making this a cozy spot for relaxed gatherings.`,
    address:
      "32 President Quirino Street, Villa Aurora Subdivision, Kasambagan, Cebu, Cebu, 6000, Philippines",
    contact: "+63 919 064 1004",
    email: "",
    website: "https://www.instagram.com/abaseriadeliandcafe/",
    image: "assets/abaseria_deli_cafe1.jpg",
  },
  {
    id: "some_thai",
    name: "SOME THAI",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.632361, lng: 121.034417 },
    description: `A cheerful dining space inspired by modern Thai cafés. The menu brings together popular Thai dishes like papaya salad, pad thai, and spicy curries, all presented in a lighter, contemporary style. The playful design and approachable flavors make it great for casual dining.`,
    address:
      "195 Tomas Morato, Scout Fuentebella Street, Quezon - Metro Manila, Philippines",
    contact: "+63 976 439 4356",
    email: "",
    website: "https://www.instagram.com/somethaiph/",
    image: "assets/some_thai1.jpg",
  },
  {
    id: "morning_sun_eatery",
    name: "Morning Sun Eatery",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.620528, lng: 121.071667 },
    description: `A simple roadside spot serving Ilocano comfort food in a turo-turo style. Diners choose from classic dishes like pinakbet, skewers, and coconut-based stews. The flavors are straightforward and homey — warm, filling meals that feel true to tradition.`,
    address:
      "120 J.P. Rizal, Project 4, Quezon - Metro Manila, 1109, Philippines",
    contact: "+63 962 523 8404",
    email: "",
    website: "https://www.facebook.com/MSLE1996/",
    image: "assets/morning_sun_eatery1.jpg",
  },
];
