const restaurants = [
  {
    id: "helm",
    name: "Helm",
    stars: 2,
    category: "two_star",
    categoryText: "Two-MICHELIN-Starred Restaurant",
    location: { lat: 14.5579, lng: 121.02525 },
    description:
      "This modern restaurant reflects the chef’s half-British, half-Filipino roots and Spanish influences, blending creativity with precision. The themed, seasonal set menus range from street food to film-inspired surprises; the experience is always evolving yet consistently refined.",
    address:
      "3F, The Shops at Ayala Triangle Gardens, Makati Avenue, Makati City, Metro Manila, Philippines",
    contact: "+63 915 909 8647",
    email: "helm.reservations@gmail.com",
    website: "https://www.joshboutwood.net/restaurants/helm",
    image: "assets/helm1.jpg",
  },
  {
    id: "celera",
    name: "Celera",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.5669, lng: 121.008 },
    description: `"Celera" means "appetite" in Malay. This dimly lit restaurant serves contemporary Asian dishes with Japanese, Chinese, and Singaporean influences. Expect umami-rich creations using dashi, fermentation, and subtle smoke — with artful plating and warmly hospitable service.`,
    address:
      "3F, Comuna, 238 Pablo Ocampo Extension, Makati, Metro Manila, 1203, The Philippines",
    contact: "+63 917 501 3077",
    email: "reservations@restaurantcelera.com",
    website: "https://restaurantcelera.com/",
    image: "assets/celera1.jpg",
  },
  {
    id: "hapag",
    name: "Hapag",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.564583, lng: 121.036944 },
    description:
      '"Hapag", meaning "family table" in Tagalog, is led by a team of young chefs aspiring to reimagine Filipino cuisine with finesse. Tapping into the full potential of local ingredients, they bring a modern, sophisticated touch to traditional dishes. This inventive approach honours regional recipes and time-honoured methods, while challenging expectations and blurring culinary boundaries for a fresh and exciting perspective on Filipino flavours."',
    address:
      "7th floor, The Balmori Suites Hidalgo Drive, Rockwell Center, Makati, Metro Manila, Philippines",
    contact: "+63 917 888 5757",
    email: "hello@hapagmnl.com",
    website: "https://www.hapagmnl.com/",
    image: "assets/hapag1.jpg",
  },
  {
    id: "linamnam",
    name: "Linamnam",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.473583, lng: 121.041639 },
    description:
      "Working solo in his kitchen in the garden, the chef serves 10 diners in what was once his childhood bedroom and is now an elegant dining space with woven wall coverings, wooden floors and Tiffany-style lamps. Deeply personal dishes are rooted in regional tradition, shaped by the chef's philosophy. Think lamb dumplings in pork broth, blue marlin in fish head stock or turon with aged banana and jackfruit. Dining at this hidden gem is truly memorable.",
    address:
      "31, Greenvale 2, Marcelo Green Village, Parañaque, Metro Manila, Philippines",
    contact: "+63 917 573 0246",
    email: "",
    website: "https://linamnammnl.cococart.co/",
    image: "assets/linamnam1.jpg",
  },
  {
    id: "asador_alfonso",
    name: "Asador Alfonso",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.473583, lng: 121.041639 },
    description:
      'About 80 kilometers from Metro Manila, this modern, minimalist property takes inspiration from Taal Volcano and sits on nine hectares of lush fields. Spanish chef Rodrigo Andres Osorio helms at the kitchen, ingredients sourced directly from Spain to deliver authentic dishes that balance rustic simplicity with remarkable depth and charact. Highlights include melt-in-your-mouth house-aged A5 Wagyu ham "Jamon de Wagyu" and the classic roasted suckling pig "Cochinillo", both showcasing the chef’s dedication to tradition and craftsmanship. Warm service, genuine hospitality, and a splendid atmosphere creates the perfect setting to escape the bustle of the city and immerse yourself in a truly memorable gastronomic journey.',
    address: "Lot-3308, Barangay Road, Alfonso, Cavite, Philippines",
    contact: "+63 917 150 7621",
    email: "reservations@asadoralfonso.com",
    website: "https://www.asadoralfonso.com/",
    image: "assets/asador_alfonso1.jpg",
  },
  {
    id: "kasa_palma",
    name: "Kása Palma",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.565972, lng: 121.034389 },
    description:
      "Step into this tranquil oasis of straw cloche lamps, lush greenery and shell-lined walls evoking beachside charm. Chef Isip draws on French technique and global influences – from Latin America to Southeast Asia – and makes good use of the wood fire. Local ingredients go into expressive, refined dishes. Order a tasting menu and dine on the breezy terrace or sit at the counter and enjoy à la carte creativity and a front-row seat to the action in the open kitchen.",
    address: "6042 R. Palma, Poblacion, Makati - Metro Manila, Philippines",
    contact: "+63 917 155 9669",
    email: "reservations@asadoralfonso.com",
    website: "https://www.instagram.com/kasapalma",
    image: "assets/kasa_palma1.jpg",
  },
  {
    id: "gallery_by_chele",
    name: "Gallery by Chele",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.559, lng: 121.056139 },
    description:
      "Culinary excellence meets environmental integrity at Gallery by Chele, from local sourcing and waste reduction to educating diners. They forego à la carte in favour of three carefully crafted tasting menus – a lunch set menu, plus a six or 10-course menu in a vegetarian or fish/meat variant – that showcase Filipino ingredients through indigenous produce and partnerships with local farmers and fishermen.",
    address:
      "5F, Clipp Center, 11th Avenue corner 39th Street, Bonifacio Global City, Taguig - Metro Manila, Philippines",
    contact: "+63 917 546 1673",
    email: "reservations@gallerybychele.com",
    website: "https://gallerybychele.com/",
    image: "assets/gallery_by_chele1.jpg",
  },
  {
    id: "toyo_eatery",
    name: "Toyo Eatery",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.5311389, lng: 121.0226389 },
    description: `"Toyo", Tagalog for "soy sauce", hints at the restaurant's appreciation of apparently simple items that in fact take time and are complex to craft. Ingredients are sourced exclusively from the Philippines; fermenting and preserving is done on site. The chef balances seasoning – soy, vinegar and fish sauce – to enhance the dishes and highlight the natural flavours. For a traditional experience, try kamayan: a shared meal served on banana leaf, eaten with your hands.`,
    address:
      "The Alley at Karrivin, Karrivin Plaza, 2316 Chino Roces Avenue Extension, Makati - Metro Manila, Philippines",
    contact: "+63 917 546 1673",
    email: "reservations@toyoeatery.com",
    website: "https://toyoeatery.com/",
    image: "assets/toyo_eatery1.jpg",
  },
  {
    id: "inato",
    name: "Inatô",
    stars: 1,
    category: "one_star",
    categoryText: "One-MICHELIN-Starred Restaurant",
    location: { lat: 14.5313056, lng: 121.02275 },
    description: `Located in The Alley, a buzzing part of Karrivin, this discreet gem blends intimacy with finesse. Ring the bell to enter a chic space in which a sculptural marble counter seats eight facing the open kitchen. Light floors, wooden slats and a textured feature wall add modern charm. Chef JP Cruz reimagines Filipino cuisine with flair. Standouts include yellowtail amberjack and choco tarte – delivered with seamless, warm interaction in a calm, elegant setting.`,
    address:
      "The Alley at Karrivin, Karrivin Plaza, 2316 Chino Roces Avenue Extension, Makati - Metro Manila, 1231, Philippines",
    contact: "+63 945 478 0420",
    email: "reservations@inato.ph",
    website: "https://www.inato.ph/",
    image: "assets/inato1.jpg",
  },
  {
    id: "em_hanoi",
    name: "Em Hà Nội",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.553444, lng: 121.04925 },
    description: `This modest, family-style eatery in Taguig brings the charm of Hanoi to Manila with a menu of Vietnamese favourites. Expect comforting bowls of phở gà, a crisp nem rán appetiser and fragrant rice noodles with grilled pork. There aren't any desserts, but the bánh mì makes for a speedy, satisfying takeaway. Its name, an affectionate nod to Vietnam's capital, reflects the warmth and soul you will relish in every bite. Simple, sincere and quietly memorable.`,
    address:
      "GF, F1 Hotel, 32nd Street corner Lane A, Bonifacio Global City, Taguig - Metro Manila, 1226, The Philippines",
    contact: "+63 981 046 9999",
    email: "emhanoi.mnl@gmail.com",
    website: "https://www.instagram.com/emhanoi.mnl",
    image: "assets/em_hanoi1.jpg",
  },
  {
    id: "palm_grill",
    name: "Palm Grill (Diliman)",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.629167, lng: 121.034111 },
    description: `Woven tablecloths and ethnic-inspired music set the tone in this cosy place. Expect warm hospitality and classic Southern Mindanao cuisine, which uses spices, acidity and roasted coconut for rich, intense flavours, for example the generously sized tiyula itum stew with beef simmered in coconut broth for a hint of acidity and smoky aroma. The Dulang – an exquisite platter of seven dishes in tasting portions – provides an excellent and varied introduction.`,
    address:
      "GF, F1 Hotel, 32nd Street corner Lane A, Bonifacio Global City, Taguig - Metro Manila, 1226, The Philippines",
    contact: "+63 908 180 4701",
    email: "palatablechicken@gmail.com",
    website: "https://www.instagram.com/palmgrillph",
    image: "assets/palm_grill1.jpg",
  },
  {
    id: "lampara",
    name: "Lampara",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.563833, lng: 121.032083 },
    description: `Discreetly situated on a quiet side street, Lampara welcomes diners with its softly glowing sign and bistro charm. The mood inside, and out on the terrace, is relaxed and inviting. Ingredient-led dishes showcase classic French techniques infused with Filipino touches. Think: octopus, soft shell crab or tofu rice cups. The desserts, both artful and indulgent, are not to be missed! Cordial service completes this quietly confident neo-Filipino gem.`,
    address:
      "2F, 5883 Enriquez Street, Poblacion, Makati - Metro Manila, 1210, Philippines",
    contact: "+63 917 173 5883",
    email: "restaurantlampara@gmail.com",
    website: "https://www.instagram.com/lampara.pob",
    image: "assets/lampara1.jpg",
  },
  {
    id: "your_local",
    name: "Your Local",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 14.556861, lng: 121.017111 },
    description: `This understated, centrally located eatery is buzzing! Behind an unassuming entrance, the neat space has butcher-tiled walls, exposed ceilings and wooden bistro-style tables. Your Local has its finger on the pulse, serving easy-going, wallet-friendly gastronomy including dishes that are ideal for sharing. Try the miso tuna tartare with gochujang and calamansi and the meltingly tender braised lamb shoulder with soy anise sauce – both packed with flavour.`,
    address: "106 Esteban, Legazpi Village, Makati - Metro Manila, Philippines",
    contact: "+63 977 487 9236",
    email: "hello@yourlocal.ph",
    website: "https://www.instagram.com/yourlocalph",
    image: "assets/your_local1.jpg",
  },
  {
    id: "cur8",
    name: "CUR8",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.340806, lng: 123.912583 },
    description: `Designed by a Filipino architect, this stylish destination pairs grey tones with turquoise accents and club beats for a modern, casual feel. CUR8, is a nod to the chef behind the concept – where Asian cuisine is reimagined with bold style. Featuring clear categories, from Best Seller to Chef's Recommendation and Healthy Option, the menu is approachable. The lunch set, showcasing various dishes as small portions, is a fantastic deal.`,
    address:
      "Banilad Town Center, Governor M. Cuenco Avenue, Cebu, Cebu, 6000, The Philippines",
    contact: "+63 977 328 0280",
    email: "",
    website: "https://www.instagram.com/CUR8.PH",
    image: "assets/cur81.jpg",
  },
  {
    id: "sarsa",
    name: "Sarsa",
    stars: "0",
    category: "bib_gourmand",
    categoryText: "Bib Gourmand Restaurant",
    location: { lat: 10.340806, lng: 123.912583 },
    description: `Lunchtime sees this modest restaurant packed to the rafters. Marbled tiles, rattan lamps, simple wooden tables and casual seating make for a laid-back vibe. Green-accented walls and screen dividers offer structure, but the focus is firmly on flavour over form. Generous sharing portions of Filipino staples such as kinilaw and lechon manok are crowd-pleasers, while the turon a la mode is a sweet final flourish. Unfussy, authentic and excellent value.`,
    address:
      "Banilad Town Center, Governor M. Cuenco Avenue, Cebu, Cebu, 6000, The Philippines",
    contact: "+63 977 328 0280",
    email: "",
    website: "https://www.instagram.com/CUR8.PH",
    image: "assets/cur81.jpg",
  },
];
